version: "3"

services:
  hhp:
    build:
      context: "./"
    container_name: "hhp"
    ports:
      - 8078:80
    networks:
      - hhp-net
    depends_on:
      - db
    env_file:
      - "./compose_data/local/hhp.env"

  db:
    build:
      context: "./db_data"
    container_name: "hhp-db"
    networks:
      - hhp-net
    ports:
      - "5432:5432"  # 호스트 포트와 컨테이너 포트 매핑
    env_file:
      - "./compose_data/local/hhp-db.env"
    environment:
      POSTGRES_USER: lshh
      POSTGRES_PASSWORD: lshh.com
      POSTGRES_DB: api_repository
    volumes:
      - ../db/pgdata:/var/lib/postgresql/data    

networks:
  hhp-net: