# server
server:
    port: 80
    servlet:
        application-display-name: hhp-local
# Spring
spring:
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 300MB
            max-request-size: 315MB
            location: /DATA/upload

# 액추에이터
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

# 스웨거
springdoc:
    api-docs:
        enabled: true