server:
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

# Spring
spring:
    #profiles
    profiles:
        active: 
        - local
        # - dev
        # - stg
        # - prod
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher

springdoc:
    swagger-ui:
        groups-order: DESC
        doc-expansion: none
        tags-sorter: alpha
        operationsSorter: method
        display-request-duration: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json


