# server
server:
  port: 3000
  servlet:
    application-display-name: hhp-local
# Spring
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  # Database
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://172.30.1.11:5432/hhp_db
     username: lshh
     password: lshh.com
  sql:
     init:
       platform: postgres
  jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     generate-ddl: false
     hibernate:
       ddl-auto: none
     show-sql: true
     properties:
       hibernate:
         format_sql: true

# 액추에이터
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          - "*"
          # - health
          # - info
  info:    
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# 스웨거
springdoc:
  api-docs:
    enabled: true
