# server
server:
  port: 80
  servlet:
      application-display-name: hhp-local
# Spring
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

# 액추에이터
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          - "*"
          # - health
          # - info
  info:    
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# 스웨거
springdoc:
  api-docs:
    enabled: true
