server:
  port: 3000
  servlet:
    application-display-name: hhp

# spring:
#   # Database
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: ${SPRING_DATASOURCE_URL}
#     username: ${SPRING_DATASOURCE_USERNAME}
#     password: ${SPRING_DATASOURCE_PASSWORD}
#   sql:
#     init:
#       platform: postgres
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     generate-ddl: false
#     hibernate:
#       ddl-auto: none
#     show-sql: false
#     properties:
#       hibernate:
#         format_sql: true

# 액추에이터 설정
management:
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health

# 스웨거 설정
springdoc:
  api-docs:
    enabled: false
