server:
  port: 3000
  servlet:
    application-display-name: hhp
spring:
  datasource:
    url: jdbc:h2:mem:test # h2 support in-memory-db
    #    url: jdbc:hsqldb:mem:yourdbname;sql.syntax_mys=true
    username: lshh
    password: lshh.com
    driver-class-name: org.h2.Driver

  jpa:
    #    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


# 액추에이터 설정
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# 스웨거 설정
springdoc:
  api-docs:
    enabled: true
