server:
    port: 80
    servlet:
        application-display-name: hhp-stg

# 액추에이터 설정
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

# 스웨거 설정
springdoc:
    api-docs:
        enabled: true

