server:
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

# Spring
spring:
    #profiles
    profiles:
        active:
#            - local2
#            - local
#            - compose
            - aws
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 300MB
            max-request-size: 315MB
            location: /DATA/upload
    # Hikari
    hikari:
        connection-test-query: SELECT 1 FROM DUAL
        connection-timeout: 600000
        maximum-pool-size: 500
        max-lifetime: 1800000
        minimum-idle: 20
        validation-timeout: 3000
        idle-timeout: 60000

springdoc:
    swagger-ui:
        groups-order: DESC
        doc-expansion: none
        tags-sorter: alpha
        operationsSorter: method
        display-request-duration: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json


