# server
server:
  port: 80
  servlet:
    application-display-name: hhp-compose
# Spring
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  # Redis
#  data:
#    redis:
#      host: ${SPRING_DATA_REDIS_HOST}
#      port: ${SPRING_DATA_REDIS_PORT}
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
  #   url: ${SPRING_DATASOURCE_URL}
  #   username: ${SPRING_DATASOURCE_USERNAME}
  #   password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        format_sql: true



# 액추에이터
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          - "*"
          # - health
          # - info
  info:    
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# 스웨거
springdoc:
  api-docs:
    enabled: true
