name: Docker Image CI to ECR - dev

on:
  push:
    branches: [ "ch3st1_aws" ]
  # pull_request:
  #   branches: [ "dev" ]

env:
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    # aws 접속
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # ecr 접근
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # ecs 띄우기 - task 정의
    - name: Render ECS task-definition
      id: render-task-definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./.aws/ecr/task/task_ch3st1.json
        container-name: container-hhp-prod
        image: ${{ steps.login-ecr.outputs.registry }}/hhp-ecr

    # ecs 띄우기 - 배포
    - name: Deploy Amazon ECS task-definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
        cluster: cluster-hhp-prod
        service: service-hhp-prod
        wait-for-service-stability: false
