name: Docker Image CI - dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    # 도커허브 접속
    - name: login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: docker.io

    # 이미지 빌드
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hhp-app:$(date +%s)
          
    # 실패 처리
    - name: Check build logs if the build fails
      if: steps.build.outcome != 'success'
      run: echo "빌드 실패!" && docker buildx logs --no-trunc hhp-app:$(date +%s)

    # 성공 처리
    - name: Push the Docker image to Docker Hub
      if: steps.build.outcome == 'success'
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hhp-app:$(date +%s)
